# YAML definition for travis-ci.com continuous integration.
# See https://docs.travis-ci.com/user/languages/c

language: c

compiler:
    - gcc

addons:
    apt:
        packages:
            libclang-3.8-dev

before_script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -G 'Unix Makefiles' ..

script:
    - make VERBOSE=1
